name: Publish

on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  version-check:
    # We need this job to run only on push with tag.
    if: ${{ github.event_name == 'push' && startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-20.04
    steps:
      - name: Check module version
        uses: tarantool/actions/check-module-version@master
        with:
          module-name: 'graphql'

  publish-rockspec-scm-1:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: graphql-scm-1.rockspec

  publish-rockspec-tag:
    if: startsWith(github.ref, 'refs/tags/')
    needs: version-check
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: tarantool/setup-tarantool@v1
        with:
          tarantool-version: '2.8'

      - run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV
      - run: tarantoolctl rocks new_version --tag $TAG
      - run: tarantoolctl rocks make graphql-$TAG-1.rockspec
      - run: tarantoolctl rocks pack graphql $TAG

      - uses: tarantool/rocks.tarantool.org/github-action@master
        with:
          auth: ${{ secrets.ROCKS_AUTH }}
          files: |
            graphql-${{ env.TAG }}-1.rockspec
            graphql-${{ env.TAG }}-1.all.rock
